DjangoView/App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url('hello', views.hello, name='hello'),
    url('getname', views.get_name, name='get_name'),
    url('getinfo', views.get_info, name='get_info'),
    url('setcookie', views.set_cookie,name='set_cookie'),
    url('getcookie', views.get_cookie, name='get_cookie'),
]

DjangoView/DjangoView/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include(('App.urls', 'App'), namespace='App')),
    path('two/', include(('Two.urls', 'Two'), namespace='two')),
]

DjangoView/Two/urls.py
from django.conf.urls import url

from Two import views

urlpatterns = {
    url('hello/', views.hello, name='hello'),
    url('login/', views.login, name='login'),
    url('mine/', views.mine, name='mine'),
    url('register/', views.register, name='register'),
    url('studentlogin/', views.student_login, name='studentlogin'),
    url('studentmine/', views.student_mine, name='studentmine'),
}

DjangoView/App/models.py
from django.db import models

# Create your models here.

DjangoView/Two/models.py
from django.db import models


class Student(models.Model):
    s_name = models.CharField(max_length=16, unique=True)
    s_password = models.CharField(max_length=128)
    s_token = models.CharField(max_length=256)

DjangoView/App/views.py
import random

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse


def hello(request):
    # HttpResponse 的属性
    response = HttpResponse()
    # response.content = 'hello Django!'
    # response.status_code = 404
    # HttpResponse 方法
    response.write("nice to meet you!")
    response.flush()  # 清除缓冲区
    return response


def get_name(request):
    # if random.randrange(10) > 5:   重定向
    #   return HttpResponseRedirect('/app/hello/')
    url = reverse('App:hello')
    return HttpResponseRedirect(url)


def get_info(request):
    data = {
        "status": 200,
        "msg": 'ok',
    }
    return JsonResponse(data=data)


def set_cookie(request):
    response = HttpResponse("set cookies")
    response.set_cookie('username', 'okinawa')
    return response


def get_cookie(request):
    username = request.COOKIES.get('username')
    return HttpResponse(username)

DjangoView/Two/views.py
import hashlib
from datetime import time
from random import random

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from Two.models import Student


def hello(request):
    return HttpResponse('hello Two')


def login(request):
    if request.method == 'GET':
        return render(request, 'two_login.html')
    elif request.method == 'POST':
        username = request.POST.get("username")
        request.session["username"] = username
        return HttpResponse("success")


def mine(request):
    username = request.session.get("username")
    return HttpResponse(username)


def register(request):
    if request.method == "GET":
        return render(request, 'student_register.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        try:
            student = Student()
            student.s_name = username
            student.s_password = password
            student.save()

        except Exception as e:
            return redirect(reverse("two:register"))

        return HttpResponse("success")


def student_login(request):
    if request.method == 'GET':
        render(request, 'student_login.html')
    elif request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        students = Student.objects.filter(s_name=username).filter(s_password=password)
        if students.exists():
            student = students.first()
            ip = request.META.get("REMOTE_ADDR")
            token = generate_token(ip)
            student.s_token = token
            student.save()
            response = HttpResponse("login ok")
            response.set_cookie("token", token)
            return response
        return redirect(reverse("two: student_login"))


def generate_token(ip, username):
    c_time = time.ctime()
    r = username
    return hashlib.new("md5", (ip + c_time + r).encoder('utf-8')).hexdigest()


def student_mine(request):
    token = request.COOKIES.get('token')
    try:
        student = Student.objects.get(s_token=token)
    except Exception as e:
        return redirect("two: student_login")

    return HttpResponse(student.s_name)

DjangoView/templates/student_login.html
!
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>StudentLogin</title>
</head>
<body>
    <form action="two/student_login" method="post">{% csrf_token %}
        <span>username:</span><input type="text" name="username" placeholder="please input username">
        <br>
        <span>password</span><input type="text" name="password" placeholder="please input your password">
        <br>
        <button>login</button>
    </form>
</body>
</html>

DjangoView/templates/student_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>studentregister</title>
</head>
<body>
<form action="two/register" method="post">{% csrf_token %}
    <span>username:</span><input type="text" name="username" placeholder="please input your name">
    <br>
    <span>passwd</span><input type="text" name="password"placeholder="please input your passwd">
    <br>
    <button>register</button>
</form>
</body>
</html>

DjangoView/templates/two_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
{#<form action="{% url 'two:login' %}" method="POST">#}
     <form action="/two/login/" method="post">{% csrf_token %}
    <span>username:</span><input type="text" placeholder="please input username" name="username">
    <br>
    <button>login</button>
</form>
</body>
</html>